file(COPY "${CPACK_PACKAGE_DIRECTORY}/../Compilation/linux/run_client.sh" DESTINATION "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/.")
file(COPY "${CPACK_PACKAGE_DIRECTORY}/../Compilation/linux/run_server.sh" DESTINATION "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/.")
