//
// Created by edo on 23/12/23.
//

#ifndef R_TYPE_COMPONENTLIST_HPP
#define R_TYPE_COMPONENTLIST_HPP

#include "rtype/components/PositionComponent.hpp"

namespace rtype
{
    enum ComponentList {
        POSITION_COMPONENT = 0,
        ANIM_COMPONENT,
        SPRITE_COMPONENT,
        COLLIDER_COMPONENT,
        PLAYER_COMPONENT,
        MYPLAYER_COMPONENT,
        ENEMY_COMPONENT,
        BULLET_COMPONENT,
        HEALTH_COMPONENT,
        SCORE_COMPONENT,
        SPEED_COMPONENT,
        BOMB_COMPONENT,
        BOMB_TIMER_COMPONENT,
        BOMB_EXPLOSION_COMPONENT,
        BOMB_EXPLOSION_TIMER_COMPONENT,
        BOMB_EXPLOSION_COLLIDER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_TIMER_COMPONENT,
        BOMB_EXPLOSION_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_DAMAGE_COLLIDER_COMPONENT,
        BOMB_EXP
    } // namespace rtype

#endif // R_TYPE_COMPONENTLIST_HPP
