file(COPY "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/lib/freetype.framework" DESTINATION "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/Frameworks/.")

file(COPY "${CPACK_PACKAGE_DIRECTORY}/../Compilation/macos/run_client.sh" DESTINATION "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/.")
file(COPY "${CPACK_PACKAGE_DIRECTORY}/../Compilation/macos/run_server.sh" DESTINATION "${CPACK_TEMPORARY_INSTALL_DIRECTORY}/.")
