########################################################################################################################
#
# This workflow will be run when a new tag is pushed to the branch 'main'.
# The goal of this workflow is to:
#  - Generate a changelog
#  - Build & package the project
#  - Create a release on GitHub
#
########################################################################################################################

name: "New tag on main"
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Generate changelog"
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build & package"
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cpack -G ZIP

      - name: "Create release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            build/*.zip