########################################################################################################################
#
# The goal of this workflow is to run tests for pull request on main branch.
# It will:
#  - Check if the project builds on:
#     - windows
#     - epitechcontent/epitest-docker docker image
#  - Check if the project passes tests
#  - Check if the project is well formatted
#
########################################################################################################################

name: "Run tests for pull request on main"
on:
  pull_request:
    branches:
      - main

jobs:
  build-on-windows:
    name: "Build on windows"
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: "Make sure Cmake and a c++ compiler are installed"
#        uses: actions/setup-msbuild@v1
#
#      - name: "Build the project"
#        run: |
#          mkdir build
#          cd build
#          cmake ..
#          cmake --build .

  build-on-epitest:
    name: "Build on epitest"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: "Build the project"
#        uses: docker://epitechcontent/epitest-docker:latest
#        with:
#          args: |
#            bash -c "
#            mkdir build
#            cd build
#            cmake ..
#            cmake --build .
#            "

  run-tests:
    name: "Run tests & check clang-tidy / clang-format"
    runs-on: ubuntu-latest
    needs: [build-on-windows, build-on-epitest]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Check clang-format"
        uses: addnab/docker-run-action@v3
        with:
          image: "epitechcontent/epitest-docker:latest"
          options: "-v ${{ github.workspace }}:/usr/app"
          run: |
            cd /usr/app
            ./scripts/check-clang-format.sh

#      - name: "Run tests"
#        uses: docker://epitechcontent/epitest-docker:latest
#        with:
#          args: |
#            bash -c "
#            mkdir build
#            cd build
#            cmake ..
#            cmake --build .
#            ctest
#            "
#
#      - name: "Check clang-tidy"
#        uses: docker://epitechcontent/epitest-docker:latest
#        with:
#          args: |
#            bash -c "
#            mkdir build
#            cd build
#            cmake ..
#            cmake --build .
#            make clang-tidy
#            "
#

