name: "Push to remote & deploy to VPS"
on:
  push:
    branches:
      - main

env:
  TARGET_REPO_URL: "git@github.com:EpitechPromo2026/B-CPP-500-LIL-5-2-rtype-quentin.desmettre.git"
  DIST_SSH_KEY: ${{ secrets.DIST_SSH_PRIVATE_KEY }}
  LOCAL_SSH_KEY: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: "Push to remote"
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
              ${{ env.TARGET_REPO_URL }}
          ssh_private_key:
              ${{ env.LOCAL_SSH_KEY }}

#  deploy:
#    name: "Deploy application to VPS"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v2
#        with:
#            fetch-depth: 0
#
#      - name: Configure SSH
#        run: |
#          ls
#          mkdir -p ~/.ssh/
#          echo "$SSH_KEY" > ~/.ssh/staging.key
#          chmod 600 ~/.ssh/staging.key
#          cat >>~/.ssh/config <<END
#          Host staging
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/staging.key
#            StrictHostKeyChecking no
#          END
#        env:
#          SSH_USER: ${{ env.SSH_USER }}
#          SSH_KEY: ${{ env.DIST_SSH_KEY }}
#          SSH_HOST: ${{ env.SSH_HOST }}
#
#      - name: Pull & start the server
#        run: ssh staging 'cd /home/ubuntu/Epitech-R-Type && git pull ${{ env.TARGET_REPO_URL }} && docker-compose down --remove-orphans && docker-compose up --build &'
